Fix: BYOK with llama-stack as a library
When using a BYOK rag database and llama-stack as a library the service
blows up on start with:

```
yaml.constructor.ConstructorError: could not determine a constructor for the tag
'tag:yaml.org,2002:python/object/apply:pathlib._local.PosixPath'
  in "<unicode string>", line 122, column 16:
          db_path: !!python/object/apply:pathlib._l ...
```

And we can see in `/tmp/llama_stack_enriched_config.yaml`:

```
storage:
  backends:
    byok_rag_1_storage:
      db_path: !!python/object/apply:pathlib._local.PosixPath
        - /home/geguileo/osls/rags/llamastack/rag/vector_db/os_product_docs/faiss_store.db
      type: kv_sqlite
```

This is caused by how we define the `db_path` in our model and how it is
being used:

In `src/models/config.py` we define it as a FilePath:

```
   1563     db_path: FilePath = Field(
   1564         ...,
   1565         title="DB path",
   1566         description="Path to RAG database.",
   1567     )
```

And in `src/llama_stack_configuration.py` we use it as a `str`:
```
    138     # add new backends for each BYOK RAG
    139     for brag in byok_rag:
    140         vector_db_id = brag.get("vector_db_id", "")
    141         backend_name = f"byok_{vector_db_id}_storage"
    142         output[backend_name] = {
    143             "type": "kv_sqlite",
    144             "db_path": brag.get("db_path", f".llama/{vector_db_id}.db"),
    145         }
```

This patch fixes this in the simplest way, making the field in the BYOK
model match the other existing `db_path` field, in other words, changing
it to a `str`.